#!/usr/bin/env python3
"""
main.py — Automatic Language Conversion Utility (v2)

Entry point that wires all modules together and starts:
  • A pynput keyboard listener   (daemon thread, managed by pynput)
  • A correction worker          (daemon thread, reads from a Queue)
  • A pystray tray icon          (main thread, blocking run loop)

Decision rules (same as original, now applied to EVERY word on EVERY line):
  Rule 1 — EN layout, EN word       → no action
  Rule 2 — HE layout, HE word       → no action
  Rule 3 — EN layout, HE intent → convert chars EN→HE, switch layout to HE
  Rule 4 — HE layout, EN intent → convert chars HE→EN, switch layout to EN
"""

import logging
import os
import queue
import sys
import threading

from PIL import Image, ImageDraw
import pystray
from pynput import keyboard as kb

# Force UTF-8 for any subprocesses (pbpaste, osascript, swift binary).
os.environ["LANG"]   = "en_US.UTF-8"
os.environ["LC_ALL"] = "en_US.UTF-8"

try:
    from ApplicationServices import AXIsProcessTrusted  # type: ignore[import]
except ImportError:
    AXIsProcessTrusted = None

from config import LOG_FILE, TRIGGER_PUNCT, ICON_PATH
from word_buffer import WordBuffer
from converter import Converter
from spell_checker import SpellChecker
from layout_switcher import LayoutSwitcher
from keyboard_replacer import KeyboardReplacer


# ── Logging setup ─────────────────────────────────────────────────────────────

def _setup_logging() -> None:
    os.makedirs(os.path.dirname(LOG_FILE), exist_ok=True)
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(LOG_FILE, encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )

_setup_logging()
log = logging.getLogger(__name__)


# ── Core application ──────────────────────────────────────────────────────────

class LanguageConverter:
    """
    Orchestrates key listening, word detection, and automatic correction.

    Threading model
    ───────────────
    • Listener thread (pynput) — calls on_press() for every key event.
      Writes to WordBuffer and puts jobs on _job_queue. Extremely fast,
      never blocks.

    • Worker thread — reads jobs from _job_queue, runs detection and
      conversion logic, calls KeyboardReplacer. May block briefly during
      the OS layout switch.

    • Main thread — runs the pystray tray icon event loop.

    Shared state
    ────────────
    • WordBuffer  — protected by an internal threading.Lock.
    • _job_queue  — thread-safe by design (queue.Queue).
    • replacer._pending — atomic int protected by a Lock; consumed one-by-one
      by the listener via consume_synthetic() to suppress synthetic events.
    """

    def __init__(self) -> None:
        log.info("=== Language Converter v2 starting ===")

        self.buffer      = WordBuffer()
        self.converter   = Converter()
        self.spell       = SpellChecker()
        self.switcher    = LayoutSwitcher()
        self.replacer    = KeyboardReplacer(self.switcher)
        self._job_queue: queue.Queue[tuple[str, str]] = queue.Queue()

        self._start_worker()

    def _start_worker(self) -> None:
        t = threading.Thread(target=self._worker_loop, name="correction-worker", daemon=True)
        t.start()
        log.info("Correction worker thread started")

    # ── Key listener callback (runs in pynput's listener thread) ─────────────

    def on_press(self, key: kb.Key) -> bool | None:
        """
        Called by pynput for every physical key press.

        Returns False only on Escape (stops the listener / exits app).
        Synthetic events fired by KeyboardReplacer are suppressed by calling
        consume_synthetic(), which atomically decrements a pre-set counter.
        This avoids the timing race that threading.Event had: controller.type()
        posts events asynchronously, so some could arrive after is_busy was
        cleared, slip through, and trigger a spurious correction in reverse.
        """
        # consume_synthetic() returns True if this event was generated by us.
        # It also decrements the internal counter, so no event is skipped twice.
        if self.replacer.consume_synthetic():
            return None

        if key == kb.Key.esc:
            return False

        try:
            if key == kb.Key.backspace:
                self.buffer.backspace()

            elif key == kb.Key.space:
                self._maybe_enqueue(" ")

            elif key == kb.Key.enter:
                self._maybe_enqueue("\n")

            elif hasattr(key, "char") and key.char is not None:
                char = key.char
                # Only accumulate printable characters.
                if not char.isprintable():
                    return None
                if char in TRIGGER_PUNCT:
                    self._maybe_enqueue(char)
                else:
                    self.buffer.add(char)

        except Exception as exc:
            log.error(f"on_press error: {exc}")

        return None

    def _maybe_enqueue(self, trigger: str) -> None:
        """Flush the buffer and enqueue a correction job if the word is non-empty."""
        word = self.buffer.flush()
        if word:
            self._job_queue.put((word, trigger))

    # ── Worker loop (runs in correction-worker thread) ────────────────────────

    def _worker_loop(self) -> None:
        while True:
            try:
                word, trigger = self._job_queue.get(timeout=1.0)
                self._process_word(word, trigger)
            except queue.Empty:
                continue
            except Exception as exc:
                log.error(f"Worker error: {exc}", exc_info=True)

    def _process_word(self, word: str, trigger: str) -> None:
        """Apply the four detection rules and trigger a replacement if needed."""
        layout = self.converter.detect_layout(word)
        if not layout:
            log.debug(f"Skipping '{word}': no recognisable script")
            return

        log.info(f"Processing '{word}' (layout={layout}, trigger={repr(trigger)})")

        if layout == "en":
            if self.spell.is_english(word):
                # Rule 1: correct layout, correct word — nothing to do.
                log.info(f"  → Rule 1: '{word}' is English, no change")
            else:
                # Rule 3: typed with English keys but likely meant Hebrew.
                # Guard: never flip the OS layout for a single character — too
                # ambiguous, and the most common cause of back-and-forth toggling.
                if len(word) < 2:
                    log.info(f"  → Skipping '{word}': single char, too ambiguous to switch")
                    return
                converted = self.converter.en_to_hebrew(word)
                log.info(f"  → Rule 3: EN→HE '{word}' → '{converted}'")
                self.replacer.replace(word, converted, trigger, "he")

        elif layout == "he":
            converted = self.converter.he_to_english(word)
            if self.spell.is_english(converted):
                # Rule 4: typed with Hebrew keys but likely meant English.
                if len(word) < 2:
                    log.info(f"  → Skipping '{word}': single char, too ambiguous to switch")
                    return
                log.info(f"  → Rule 4: HE→EN '{word}' → '{converted}'")
                self.replacer.replace(word, converted, trigger, "en")
            else:
                # Rule 2: typed with Hebrew keys for a Hebrew word — nothing to do.
                log.info(f"  → Rule 2: '{word}' is Hebrew, no change")


# ── Tray icon ─────────────────────────────────────────────────────────────────

def _create_tray_image() -> Image.Image:
    """Load the app icon or generate a simple fallback."""
    if os.path.exists(ICON_PATH):
        try:
            return Image.open(ICON_PATH)
        except Exception as exc:
            log.warning(f"Could not load icon from {ICON_PATH}: {exc}")

    # Minimal fallback: dark background with "EN/HE" text.
    img  = Image.new("RGBA", (64, 64), (28, 28, 28, 255))
    draw = ImageDraw.Draw(img)
    draw.text((4,  18), "EN", fill=(100, 200, 255, 255))
    draw.text((32, 18), "HE", fill=(255, 150, 100, 255))
    return img


def _on_quit(icon: pystray.Icon, _item: pystray.MenuItem) -> None:
    icon.stop()
    os._exit(0)


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    log.info("Starting Automatic Language Conversion Utility v2")

    app = LanguageConverter()

    # Warn if Accessibility permission is missing (keyboard replacement won't work).
    if AXIsProcessTrusted is not None:
        trusted = AXIsProcessTrusted()
        if trusted:
            log.info("Accessibility permission: GRANTED ✓")
        else:
            log.warning(
                "Accessibility permission: DENIED — "
                "go to System Settings > Privacy & Security > Accessibility "
                "and enable this app."
            )
    else:
        log.warning("Could not verify Accessibility permission (ApplicationServices unavailable)")

    # Start the keyboard listener in a background daemon thread.
    listener = kb.Listener(on_press=app.on_press)
    listener.daemon = True
    listener.start()
    log.info("Keyboard listener active — ready")

    # Run the tray icon on the main thread (required by macOS AppKit).
    icon = pystray.Icon(
        "LangSwitcher",
        _create_tray_image(),
        "Language Switcher",
        menu=pystray.Menu(pystray.MenuItem("Quit", _on_quit)),
    )
    icon.run()


if __name__ == "__main__":
    main()
